---
- name: Install Zabbix Agent via Role
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_agent
  vars:
    zabbix_agent_version: 6.0
    zabbix_agent2: false
    zabbix_agent_hostname: "bastion"
    zabbix_agent_listenip: "{{ ansible_host }}"
    zabbix_agent_server: "192.168.42.2,172.16.0.0/12,10.10.42.0/30"
    zabbix_agent_serveractive: 192.168.42.2
    zabbix_agent_host_state: present
...