[bastion]
localhost ansible_connection=local ansible_host=192.168.42.5

[zabbix_servers]
zabbix-appliance ansible_host=192.168.42.2

[managed_nodes:children]
zabbix_servers

[all:vars]
ansible_user=vagrant
ansible_ssh_pass=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'